---
- name: Ensure global Drush folder
  file: path=/etc/drush/ state=directory
  tags: [drush]
- name: Global Drush configuration (drushrc) file
  template: src=drushrc.j2 dest=/etc/drush/drushrc.php validate='php -l %s'
  tags: [drush]
